CREATE TABLE CONTRACT_TYPE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL
);

CREATE TABLE SERVICE_TYPE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL
);

CREATE TABLE OWNER(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IME VARCHAR(50) NOT NULL,
	PREZIME VARCHAR(50) NOT NULL,
	DATUM_RODENJA DATE NOT NULL,
	OIB VARCHAR(11) NOT NULL
);

CREATE TABLE COUNTRY(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(30) NOT NULL
);

CREATE TABLE CITY(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CITY_ZIP INT,
	CITY_NAME VARCHAR(30) NOT NULL,
    COUNTRY_ID INT NOT NULL,
    FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRY(ID)
);

CREATE TABLE ADDRESS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(50) NOT NULL,
    CITY_ID INT NOT NULL,
    FOREIGN KEY(CITY_ID) REFERENCES CITY(ID)
);

CREATE TABLE SERVICE_PROVIDER(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	ADDRESS_ID INT NOT NULL,
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID)
);

CREATE TABLE HOUSEHOLD(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(50) NOT NULL
);

CREATE TABLE SERVICE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	SERVICE_PROVIDER_ID INT NOT NULL,
	SERVICE_TYPE_ID INT NOT NULL,
	PRICE DECIMAL(6,2),
	FOREIGN KEY(SERVICE_PROVIDER_ID) REFERENCES SERVICE_PROVIDER(ID),
	FOREIGN KEY(SERVICE_TYPE_ID) REFERENCES SERVICE_TYPE(ID)
);

CREATE TABLE CONTRACT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CONTRACT_TYPE_ID INT NOT NULL,
	HOUSEHOLD_ID INT NOT NULL,
	SERVICE_ID INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
	STATUS ENUM('ACTIVE', 'INACTIVE'),
    FOREIGN KEY(CONTRACT_TYPE_ID) REFERENCES CONTRACT_TYPE(ID),
	FOREIGN KEY(HOUSEHOLD_ID) REFERENCES HOUSEHOLD(ID),
	FOREIGN KEY(SERVICE_ID) REFERENCES SERVICE(ID)
);

CREATE TABLE HOUSEHOLD_OWNER(
	OWNER_ID INT NOT NULL,
	HOUSEHOLD_ID INT NOT NULL,
    FOREIGN KEY(OWNER_ID) REFERENCES OWNER(ID),
	FOREIGN KEY(HOUSEHOLD_ID) REFERENCES HOUSEHOLD(ID),
	PRIMARY KEY (OWNER_ID, HOUSEHOLD_ID)
);